// src/components/ui/Badge.jsx
import { cva } from "class-variance-authority";
import { cn } from "@/lib/cn";

const badgeStyles = cva(
  "inline-flex items-center gap-1.5 rounded-full px-2 py-0.5 text-[11px] font-medium tracking-tight",
  {
    variants: {
      tone: {
        neutral: "bg-ink-100 text-ink-700 ring-1 ring-inset ring-ink-200",
        accent:  "bg-accent-muted text-ink-900 ring-1 ring-inset ring-accent-ring/30",
        success: "bg-emerald-50 text-emerald-700 ring-1 ring-inset ring-emerald-200",
        warning: "bg-amber-50 text-amber-700 ring-1 ring-inset ring-amber-200",
        danger:  "bg-red-50 text-red-700 ring-1 ring-inset ring-red-200",
      },
    },
    defaultVariants: { tone: "neutral" },
  },
);

export function Badge({ className, tone, dot, children, ...props }) {
  return (
    <span className={cn(badgeStyles({ tone }), className)} {...props}>
      {dot && <DotForTone tone={tone ?? "neutral"} />}
      {children}
    </span>
  );
}

function DotForTone({ tone }) {
  const cls =
    tone === "success" ? "bg-emerald-500"
    : tone === "warning" ? "bg-amber-500"
    : tone === "danger" ? "bg-red-500"
    : tone === "accent" ? "bg-accent-ring"
    : "bg-ink-400";
  return <span className={cn("h-1.5 w-1.5 rounded-full", cls)} />;
}

// apps/desktop/src/lib/components/Badge.svelte
<script lang="ts">
  let {
    tone = "neutral",
    label,
    dot = true,
  }: {
    tone?: "neutral" | "success" | "warning" | "danger" | "accent";
    label: string;
    dot?: boolean;
  } = $props();

  const tones: Record<string, string> = {
    neutral: "border-line bg-sunken text-t2",
    success: "border-success/25 bg-success/10 text-success",
    warning: "border-warning/25 bg-warning/10 text-warning",
    danger: "border-danger/25 bg-danger/10 text-danger",
    accent:
      "border-accent-ring/40 bg-accent/15 text-accent-text dark:text-accent",
  };

  const dots: Record<string, string> = {
    neutral: "bg-t3",
    success: "bg-success",
    warning: "bg-warning",
    danger: "bg-danger",
    accent: "bg-accent-ring dark:bg-accent",
  };
</script>

<span
  class="inline-flex items-center gap-1.5 rounded-full border px-2 py-0.5 text-[11px] font-medium whitespace-nowrap {tones[tone]}"
>
  {#if dot}<span class="size-1.5 rounded-full {dots[tone]}"></span>{/if}
  {label}
</span>
