// src/components/PageHeader.jsx
import { cn } from "@/lib/cn";

// Editorial page header: small eyebrow, large display title, optional
// description, action area on the right. Used at the top of every screen.
export function PageHeader({ eyebrow, title, description, actions, className }) {
  return (
    <header className={cn("flex flex-wrap items-end justify-between gap-6 pb-8", className)}>
      <div className="min-w-0">
        {eyebrow && <p className="label-eyebrow mb-2">{eyebrow}</p>}
        <h1 className="text-display-lg text-ink-900">{title}</h1>
        {description && <p className="mt-2 text-sm text-ink-500 max-w-xl">{description}</p>}
      </div>
      {actions && <div className="flex items-center gap-2 shrink-0">{actions}</div>}
    </header>
  );
}

// apps/desktop/src/lib/components/PageHeader.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  let {
    eyebrow,
    title,
    subtitle,
    actions,
  }: {
    eyebrow?: string;
    title: string;
    subtitle?: string;
    actions?: Snippet;
  } = $props();
</script>

<header class="mb-6 flex flex-wrap items-end justify-between gap-4">
  <div class="min-w-0">
    {#if eyebrow}
      <p class="eyebrow mb-1.5">{eyebrow}</p>
    {/if}
    <h1 class="text-[26px] leading-tight font-semibold tracking-[-0.02em]">
      {title}
    </h1>
    {#if subtitle}
      <p class="mt-1 max-w-xl text-[13px] text-t2">{subtitle}</p>
    {/if}
  </div>
  {#if actions}
    <div class="flex shrink-0 items-center gap-2">{@render actions()}</div>
  {/if}
</header>
