// src/components/Sidebar.jsx
import { NavLink } from "react-router-dom";
import {
  LayoutDashboard, Receipt, Users, Settings, Plus, Search,
  Target, TrendingUp, BookOpen, BarChart3, ShieldCheck,
  Landmark, GitCompareArrows, Briefcase, Brain, CreditCard,
} from "lucide-react";
import { Wordmark } from "@/components/Wordmark";
import { Avatar } from "@/components/ui/Avatar";
import { Badge } from "@/components/ui/Badge";
import { useOrgStore } from "@/stores/org";
import { useUIStore } from "@/stores/ui";
import { useOrgs } from "@/lib/queries";
import { cn } from "@/lib/cn";

// Items shown only for team/business orgs (hidden for personal kind)
const TEAM_ONLY_ROUTES = new Set([
  "/ledger", "/reports", "/bank-feeds", "/reconcile", "/audit", "/members",
]);

const nav = [
  { to: "/dashboard", label: "Dashboard", icon: LayoutDashboard, shortcut: "g d" },
  { to: "/receipts",  label: "Receipts",  icon: Receipt,         shortcut: "g r" },
  { to: "/budgets",   label: "Budgets",   icon: Target,          shortcut: "g b" },
  { to: "/net-worth", label: "Net worth", icon: TrendingUp,      shortcut: "g n" },
  { to: "/ledger",    label: "Ledger",    icon: BookOpen,        shortcut: "g l" },
  { to: "/reports",   label: "Reports",   icon: BarChart3,       shortcut: "g p" },
  { to: "/bank-feeds",label: "Bank feeds",icon: Landmark,        shortcut: "g f" },
  { to: "/reconcile", label: "Reconcile", icon: GitCompareArrows,shortcut: "g c" },
  { to: "/insights",  label: "Insights",  icon: Brain,           shortcut: "g i" },
  { to: "/workspace", label: "Workspace", icon: Briefcase,       shortcut: "g w" },
  { to: "/audit",     label: "Audit",     icon: ShieldCheck,     shortcut: "g u" },
  { to: "/members",   label: "Members",   icon: Users,           shortcut: "g m" },
  { to: "/settings",  label: "Settings",  icon: Settings,        shortcut: "g s" },
  { to: "/billing",   label: "Billing",   icon: CreditCard,      shortcut: "g x" },
];

export function Sidebar({ onNavigate } = {}) {
  const { activeOrgId } = useOrgStore();
  const setPaletteOpen = useUIStore((s) => s.setPaletteOpen);
  const setUploadOpen = useUIStore((s) => s.setUploadOpen);
  const { data: orgs } = useOrgs();

  const active = orgs?.organizations.find((o) => o.id === activeOrgId) ?? orgs?.organizations[0];
  const isMac = typeof navigator !== "undefined" && /Mac/i.test(navigator.platform);

  // Hide team-only items when the active org is personal
  const isPersonal = active?.kind !== "business";
  const visibleNav = nav.filter((item) => !isPersonal || !TEAM_ONLY_ROUTES.has(item.to));

  return (
    <aside className="flex flex-col w-[252px] shrink-0 border-r border-ink-100 bg-ink-50/40 sticky top-[52px] h-[calc(100vh-52px)] overflow-y-auto">
      {/* Wordmark header */}
      <div className="px-4 py-4">
        <Wordmark size="sm" />
      </div>

      <div className="px-3 mb-2">
        {active && (
          <div className="w-full flex items-center gap-2 px-2 py-1.5 rounded">
            <Avatar name={active.name} size="sm" />
            <span className="flex-1 min-w-0 text-left">
              <span className="block text-sm font-medium text-ink-900 truncate tracking-tight">{active.name}</span>
              <span className="block text-[11px] text-ink-500 truncate">/{active.slug}</span>
            </span>
            {active.role === "admin" && <Badge tone="accent">Admin</Badge>}
          </div>
        )}
      </div>

      <div className="px-3 mb-3">
        <button
          onClick={() => setPaletteOpen(true)}
          className="w-full flex items-center gap-2 px-2 h-8 rounded border border-ink-200 bg-ink-0 text-[12px] text-ink-500 hover:text-ink-900 hover:border-ink-300 transition-colors"
          aria-label="Open command palette"
        >
          <Search size={13} className="text-ink-400" />
          <span className="flex-1 text-left tracking-tight">Search…</span>
          <kbd className="font-mono text-[10px] text-ink-400 border border-ink-200 rounded px-1 py-0.5">
            {isMac ? "⌘K" : "Ctrl K"}
          </kbd>
        </button>
      </div>

      <nav className="px-3 flex-1 space-y-0.5">
        {visibleNav.map((item) => (
          <NavLink
            key={item.to}
            to={item.to}
            onClick={() => onNavigate?.()}
            className={({ isActive }) =>
              cn(
                "group flex items-center gap-2.5 px-2 py-1.5 rounded text-sm transition-colors",
                isActive
                  ? "bg-ink-900 text-ink-0"
                  : "text-ink-600 hover:bg-ink-100 hover:text-ink-900",
              )
            }
          >
            {({ isActive }) => (
              <>
                <item.icon size={15} className={isActive ? "" : "text-ink-400 group-hover:text-ink-700"} />
                <span className="flex-1 tracking-tight">{item.label}</span>
                <kbd className={cn(
                  "hidden group-hover:inline text-[10px] font-mono",
                  isActive ? "text-ink-400" : "text-ink-300",
                )}>{item.shortcut}</kbd>
              </>
            )}
          </NavLink>
        ))}
      </nav>

      <div className="px-3 pb-3">
        <button
          onClick={() => { setUploadOpen(true); onNavigate?.(); }}
          className="w-full inline-flex items-center justify-center gap-2 h-9 rounded-md bg-accent text-accent-fg text-sm font-medium tracking-tight hover:bg-[#D9FF40] transition-colors shadow-card"
        >
          <Plus size={14} /> Upload receipt
          <kbd className="hidden sm:inline ml-1 font-mono text-[10px] text-accent-fg/60">U</kbd>
        </button>
      </div>
    </aside>
  );
}

// apps/desktop/src/lib/components/Sidebar.svelte
<script lang="ts">
  import logoMark from "../../assets/logo-mark.svg?raw";
  import { router, type RouteId } from "../router.svelte";
  import { theme, type ThemeMode } from "../theme.svelte";
  import { api, isTauri } from "../api/client";
  import type { Book, Health } from "../api/types";
  import type { IconName } from "../icons";
  import Icon from "./Icon.svelte";

  interface NavItem {
    route: RouteId;
    label: string;
    icon: IconName;
    key: string;
  }

  const nav: NavItem[] = [
    { route: "dashboard", label: "Dashboard", icon: "dashboard", key: "D" },
    { route: "transactions", label: "Transactions", icon: "transactions", key: "T" },
    { route: "receipts", label: "Receipts", icon: "receipt", key: "R" },
    { route: "budgets", label: "Budgets", icon: "budgets", key: "B" },
    { route: "ledger", label: "Ledger", icon: "ledger", key: "L" },
    { route: "reconcile", label: "Reconcile", icon: "reconcile", key: "C" },
    { route: "reports", label: "Reports", icon: "reports", key: "P" },
    { route: "settings", label: "Settings", icon: "settings", key: "S" },
  ];

  const themeModes: Array<{ mode: ThemeMode; icon: IconName; label: string }> = [
    { mode: "system", icon: "monitor", label: "Follow OS theme" },
    { mode: "light", icon: "sun", label: "Light theme" },
    { mode: "dark", icon: "moon", label: "Dark theme" },
  ];

  let book = $state<Book | null>(null);
  let health = $state<Health | null>(null);

  api.bookList().then((books) => (book = books[0] ?? null));
  api.health().then((h) => (health = h));
</script>

<aside
  class="flex w-60 shrink-0 flex-col border-r border-line bg-panel"
  aria-label="Primary"
>
  <!-- brand -->
  <div class="flex items-center gap-2.5 px-4 pt-4 pb-3">
    <span class="inline-flex size-8 shrink-0 rounded-[7px] ring-1 ring-line dark:ring-ink-700 [&>svg]:size-8">
      {@html logoMark}
    </span>
    <span class="text-[15px] font-semibold tracking-tight">
      slip<span class="text-accent-ring dark:text-accent">/</span>scan
    </span>
  </div>

  <!-- book -->
  <div class="mx-3 mb-3 flex items-center gap-2.5 rounded-lg border border-line px-2.5 py-2">
    <span
      class="flex size-7 shrink-0 items-center justify-center rounded-full bg-sunken text-[11px] font-semibold text-t2"
    >
      {book ? book.name.slice(0, 1).toUpperCase() : "·"}
    </span>
    <span class="min-w-0 flex-1 leading-tight">
      <span class="block truncate text-[12.5px] font-medium">
        {book?.name ?? "Loading…"}
      </span>
      <span class="block truncate text-[11px] text-t3">
        {book ? `${book.kind} · ${book.currency}` : ""}
      </span>
    </span>
    <Icon name="chevron-down" size={13} class="shrink-0 text-t3" />
  </div>

  <!-- search -->
  <div class="relative mx-3 mb-3">
    <Icon
      name="search"
      size={14}
      class="pointer-events-none absolute top-1/2 left-2.5 -translate-y-1/2 text-t3"
    />
    <input
      id="global-search"
      class="input pr-12 pl-8"
      placeholder="Search…"
      type="text"
      onkeydown={(e) => {
        if (e.key === "Enter") router.go("transactions");
        if (e.key === "Escape") e.currentTarget.blur();
      }}
    />
    <span class="pointer-events-none absolute top-1/2 right-2 -translate-y-1/2">
      <span class="kbd">⌘K</span>
    </span>
  </div>

  <!-- nav -->
  <nav class="flex-1 space-y-0.5 overflow-y-auto px-3" aria-label="Sections">
    {#each nav as item (item.route)}
      {@const active = router.current === item.route}
      <a
        href="#/{item.route}"
        aria-current={active ? "page" : undefined}
        class="group flex items-center gap-2.5 rounded-md px-2.5 py-[7px] text-[13px] font-medium transition-colors
          {active
          ? 'bg-ink-900 text-ink-50 dark:bg-ink-100 dark:text-ink-900'
          : 'text-t2 hover:bg-sunken hover:text-t1'}"
      >
        <Icon
          name={item.icon}
          size={16}
          class={active ? "" : "text-t3 group-hover:text-t2"}
        />
        <span class="flex-1">{item.label}</span>
        {#if active}
          <span class="size-1.5 rounded-full bg-accent"></span>
        {:else}
          <span
            class="kbd opacity-0 transition-opacity group-hover:opacity-100"
            title="Press G then {item.key}">{item.key}</span
          >
        {/if}
      </a>
    {/each}
  </nav>

  <!-- footer -->
  <div class="space-y-3 px-3 pt-3 pb-4">
    <button
      type="button"
      class="btn btn-primary h-9 w-full justify-center text-[13px]"
      onclick={() => router.go("receipts")}
    >
      <Icon name="upload" size={15} />
      Import receipt
    </button>

    <div class="flex items-center justify-between">
      <div
        class="flex items-center gap-0.5 rounded-md border border-line p-0.5"
        role="group"
        aria-label="Theme"
      >
        {#each themeModes as t (t.mode)}
          <button
            type="button"
            title={t.label}
            aria-pressed={theme.mode === t.mode}
            class="flex size-6 items-center justify-center rounded transition-colors
              {theme.mode === t.mode
              ? 'bg-sunken text-t1'
              : 'text-t3 hover:text-t2'}"
            onclick={() => theme.set(t.mode)}
          >
            <Icon name={t.icon} size={13} />
          </button>
        {/each}
      </div>
      <span
        class="flex items-center gap-1.5 text-[10.5px] text-t3"
        title={isTauri ? "Running under Tauri" : "Browser dev — mock data"}
      >
        <span
          class="size-1.5 rounded-full {health ? 'bg-success' : 'bg-t3'}"
        ></span>
        {health ? `v${health.version}` : "…"}{isTauri ? "" : " · mock"}
      </span>
    </div>
  </div>
</aside>
