// src/pages/Receipts.jsx
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Plus, Search, ArrowUpDown, Receipt as ReceiptIcon, AlertCircle, Download } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { EmptyState } from "@/components/ui/EmptyState";
import { Skeleton } from "@/components/ui/Skeleton";
import { StatusPill } from "@/components/StatusPill";
import { useDocuments } from "@/lib/queries";
import { useOrgStore } from "@/stores/org";
import { useUIStore } from "@/stores/ui";
import { formatDate, formatMoney, formatRelative } from "@/lib/format";
import { cn } from "@/lib/cn";
import { documentsToCSV, downloadCSV } from "@/lib/csv";
import {
  DropdownMenu, DropdownMenuTrigger, DropdownMenuContent,
  DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuCheckboxItem,
} from "@/components/ui/DropdownMenu";

export default function ReceiptsPage() {
  const orgId = useOrgStore((s) => s.activeOrgId);
  const { data, isLoading } = useDocuments(orgId);
  const setUploadOpen = useUIStore((s) => s.setUploadOpen);
  const [q, setQ] = useState("");
  const [statuses, setStatuses] = useState(new Set());
  const [sort, setSort] = useState({ key: "date", dir: "desc" });

  const docs = data?.documents ?? [];
  const filtered = useMemo(() => filter(docs, q, statuses, sort), [docs, q, statuses, sort]);

  const onExport = () => {
    if (filtered.length === 0) return;
    const csv = documentsToCSV(filtered);
    const stamp = new Date().toISOString().slice(0, 10);
    downloadCSV(`slipscan-receipts-${stamp}.csv`, csv);
    toast.success("Exported", { description: `${filtered.length} ${filtered.length === 1 ? "receipt" : "receipts"} as CSV` });
  };

  const toggleStatus = (s) => {
    setStatuses((prev) => {
      const next = new Set(prev);
      next.has(s) ? next.delete(s) : next.add(s);
      return next;
    });
  };

  const onSort = (key) => {
    setSort((prev) => prev.key === key
      ? { key, dir: prev.dir === "asc" ? "desc" : "asc" }
      : { key, dir: "desc" });
  };

  return (
    <div className="page-shell max-w-[1280px]">
      <PageHeader
        eyebrow="Workspace"
        title="Receipts"
        description="Every slip your team has uploaded. Search, filter, and click through to verify."
        actions={
          <>
            <Button
              variant="secondary"
              onClick={onExport}
              disabled={filtered.length === 0}
              title="Export current view as CSV"
            >
              <Download size={14} /> Export
            </Button>
            <Button variant="accent" onClick={() => setUploadOpen(true)}>
              <Plus size={14} /> Upload receipt
            </Button>
          </>
        }
      />

      <div className="flex flex-wrap items-center gap-2 mb-4">
        <div className="relative flex-1 min-w-[260px] max-w-[420px]">
          <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-400 pointer-events-none" />
          <Input
            placeholder="Search by merchant…"
            value={q}
            onChange={(e) => setQ(e.target.value)}
            className="pl-9"
          />
        </div>

        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="secondary" size="md">
              <span>Status</span>
              {statuses.size > 0 && <Badge tone="neutral">{statuses.size}</Badge>}
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="start">
            <DropdownMenuLabel>Filter by status</DropdownMenuLabel>
            <DropdownMenuSeparator />
            {["pending", "verified", "rejected"].map((s) => (
              <DropdownMenuCheckboxItem
                key={s}
                checked={statuses.has(s)}
                onCheckedChange={() => toggleStatus(s)}
              >
                <span className="capitalize">{s}</span>
              </DropdownMenuCheckboxItem>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>

        <div className="ml-auto text-[12px] text-ink-500 tnum">
          {!isLoading && (
            <>{filtered.length} {filtered.length === 1 ? "result" : "results"}{q || statuses.size > 0 ? ` of ${docs.length}` : ""}</>
          )}
        </div>
      </div>

      <Card className="overflow-hidden">
        {isLoading ? (
          <ListSkeleton />
        ) : filtered.length === 0 && docs.length === 0 ? (
          <EmptyState
            icon={<ReceiptIcon size={20} />}
            title="No receipts yet"
            description="Upload your first slip to get started. We'll extract the details automatically."
            action={
              <Button variant="accent" onClick={() => setUploadOpen(true)}>
                <Plus size={14} /> Upload receipt
              </Button>
            }
          />
        ) : filtered.length === 0 ? (
          <EmptyState
            title="Nothing matches"
            description="Try adjusting your search or filters."
            action={
              <Button variant="ghost" onClick={() => { setQ(""); setStatuses(new Set()); }}>
                Clear filters
              </Button>
            }
          />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-ink-100 bg-ink-50/50">
                  <Th sortable active={sort.key === "merchant"} dir={sort.dir} onClick={() => onSort("merchant")}>Merchant</Th>
                  <Th sortable active={sort.key === "date"} dir={sort.dir} onClick={() => onSort("date")}>Date</Th>
                  <Th>Status</Th>
                  <Th>Uploaded</Th>
                  <Th sortable active={sort.key === "amount"} dir={sort.dir} onClick={() => onSort("amount")} align="right">Amount</Th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((d) => <Row key={d.id} doc={d} />)}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}

function Row({ doc }) {
  return (
    <tr className="group border-b border-ink-100 last:border-0 hover:bg-ink-50/60 transition-colors">
      <td className="px-5 py-3">
        <Link to={`/receipts/${doc.id}`} className="block">
          <div className="flex items-center gap-3">
            <div className="h-8 w-8 rounded bg-ink-100 flex items-center justify-center text-ink-400 shrink-0">
              <ReceiptIcon size={14} />
            </div>
            <div className="min-w-0">
              <div className="text-sm font-medium tracking-tight text-ink-900 truncate group-hover:underline underline-offset-4 decoration-ink-300">
                {doc.merchant || <span className="italic text-ink-400">Awaiting extraction</span>}
              </div>
              {doc.extraction_error && (
                <div className="flex items-center gap-1 text-[11px] text-amber-700 mt-0.5">
                  <AlertCircle size={10} /> Extraction failed — view to retry
                </div>
              )}
            </div>
          </div>
        </Link>
      </td>
      <td className="px-5 py-3 text-ink-700 tnum">{formatDate(doc.transaction_date)}</td>
      <td className="px-5 py-3"><StatusPill status={doc.status} /></td>
      <td className="px-5 py-3 text-ink-500">{formatRelative(doc.created_at)}</td>
      <td className="px-5 py-3 text-right font-medium text-ink-900 tnum">
        {formatMoney(doc.amount, doc.currency)}
      </td>
    </tr>
  );
}

function Th({ children, align, sortable, active, dir, onClick }) {
  const cls = cn(
    "px-5 py-2.5 label-eyebrow !text-ink-500 select-none",
    align === "right" ? "text-right" : "text-left",
    sortable && "cursor-pointer hover:text-ink-900",
  );
  return (
    <th onClick={onClick} className={cls}>
      <span className={cn("inline-flex items-center gap-1", align === "right" && "justify-end")}>
        {children}
        {sortable && (
          <ArrowUpDown
            size={11}
            className={cn(
              "transition-colors",
              active ? "text-ink-700" : "text-ink-300",
              active && dir === "asc" && "rotate-180",
            )}
          />
        )}
      </span>
    </th>
  );
}

function ListSkeleton() {
  return (
    <table className="w-full">
      <tbody>
        {Array.from({ length: 8 }).map((_, i) => (
          <tr key={i} className="border-b border-ink-100">
            <td className="px-5 py-3.5">
              <div className="flex items-center gap-3">
                <Skeleton className="h-8 w-8 rounded" />
                <Skeleton className="h-3 w-32" />
              </div>
            </td>
            <td className="px-5 py-3.5"><Skeleton className="h-3 w-16" /></td>
            <td className="px-5 py-3.5"><Skeleton className="h-4 w-16 rounded-full" /></td>
            <td className="px-5 py-3.5"><Skeleton className="h-3 w-20" /></td>
            <td className="px-5 py-3.5 text-right"><Skeleton className="h-3 w-16 ml-auto" /></td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function filter(docs, q, statuses, sort) {
  const ql = q.trim().toLowerCase();
  let out = docs.filter((d) => {
    if (statuses.size > 0 && !statuses.has(d.status)) return false;
    if (!ql) return true;
    return (d.merchant || "").toLowerCase().includes(ql)
        || (d.notes || "").toLowerCase().includes(ql)
        || (d.payment_method || "").toLowerCase().includes(ql);
  });
  out = [...out].sort((a, b) => {
    const dir = sort.dir === "asc" ? 1 : -1;
    if (sort.key === "amount") return ((a.amount ?? 0) - (b.amount ?? 0)) * dir;
    if (sort.key === "merchant") return (a.merchant || "").localeCompare(b.merchant || "") * dir;
    const av = a.transaction_date || a.created_at;
    const bv = b.transaction_date || b.created_at;
    return (new Date(av).getTime() - new Date(bv).getTime()) * dir;
  });
  return out;
}

// apps/desktop/src/routes/Receipts.svelte
<script lang="ts">
  import { api } from "../lib/api/client";
  import { fmtDate, fmtMoney, fmtPct } from "../lib/format";
  import type { Document, DocumentStatus } from "../lib/api/types";
  import PageHeader from "../lib/components/PageHeader.svelte";
  import EmptyState from "../lib/components/EmptyState.svelte";
  import Skeleton from "../lib/components/Skeleton.svelte";
  import Badge from "../lib/components/Badge.svelte";
  import Icon from "../lib/components/Icon.svelte";

  type Filter = "all" | DocumentStatus;

  let docs = $state<Document[]>([]);
  let loading = $state(true);
  let filter = $state<Filter>("all");
  let search = $state("");
  let bookId = $state("");

  async function load() {
    loading = true;
    const [book] = await api.bookList();
    if (!book) return;
    bookId = book.id;
    docs = await api.documentList({ book_id: book.id });
    loading = false;
  }
  load();

  const filters: Array<{ id: Filter; label: string }> = [
    { id: "all", label: "All" },
    { id: "pending", label: "Pending" },
    { id: "extracted", label: "Extracted" },
    { id: "reviewed", label: "Reviewed" },
  ];

  const counts = $derived(
    docs.reduce(
      (acc, d) => ((acc[d.status] = (acc[d.status] ?? 0) + 1), acc),
      {} as Partial<Record<DocumentStatus, number>>,
    ),
  );

  const filtered = $derived(
    docs.filter((d) => {
      if (filter !== "all" && d.status !== filter) return false;
      if (search) {
        const s = search.toLowerCase();
        if (
          !(d.merchant ?? "").toLowerCase().includes(s) &&
          !d.file_name.toLowerCase().includes(s)
        )
          return false;
      }
      return true;
    }),
  );

  const statusTone: Record<
    DocumentStatus,
    "warning" | "accent" | "success" | "danger"
  > = {
    pending: "warning",
    extracted: "accent",
    reviewed: "success",
    failed: "danger",
  };

  async function importReceipt() {
    // Shell placeholder: real flow opens the OS file picker via Tauri.
    await api.documentImport({
      book_id: bookId,
      file_name: `scan-${Date.now().toString(36)}.pdf`,
      mime_type: "application/pdf",
    });
    docs = await api.documentList({ book_id: bookId });
  }
</script>

<PageHeader
  eyebrow="Slips · receipts · statements"
  title="Receipts"
  subtitle="Drop in slips and let extraction do the typing. Review anything below full confidence."
>
  {#snippet actions()}
    <button class="btn">
      <Icon name="download" size={14} />
      Export
    </button>
    <button class="btn btn-primary" onclick={importReceipt}>
      <Icon name="upload" size={14} />
      Import receipt
    </button>
  {/snippet}
</PageHeader>

<div class="mb-3 flex flex-wrap items-center gap-2">
  <div class="relative w-64">
    <Icon
      name="search"
      size={14}
      class="pointer-events-none absolute top-1/2 left-2.5 -translate-y-1/2 text-t3"
    />
    <input
      class="input pl-8"
      placeholder="Search by merchant or file…"
      bind:value={search}
    />
  </div>
  <div class="flex items-center gap-1" role="group" aria-label="Status filter">
    {#each filters as f (f.id)}
      <button
        class="btn h-7 px-2.5 text-[12px] {filter === f.id
          ? 'border-line-2 bg-sunken'
          : 'btn-ghost text-t2'}"
        aria-pressed={filter === f.id}
        onclick={() => (filter = f.id)}
      >
        {f.label}
        {#if f.id !== "all" && counts[f.id]}
          <span class="num text-[10.5px] text-t3">{counts[f.id]}</span>
        {/if}
      </button>
    {/each}
  </div>
  <span class="ml-auto text-[12px] text-t3">{filtered.length} results</span>
</div>

<div class="card overflow-hidden">
  {#if loading}
    <Skeleton rows={8} />
  {:else if docs.length === 0}
    <EmptyState
      icon="receipt"
      title="No receipts yet"
      body="Drag a photo or PDF anywhere in this window, forward slips to your watched mailbox, or import from a folder. Files never leave your machine."
      hint="Everything is processed locally or by the LLM provider you configure"
    >
      {#snippet actions()}
        <button class="btn btn-primary" onclick={importReceipt}>
          <Icon name="upload" size={14} />
          Import your first receipt
        </button>
      {/snippet}
    </EmptyState>
  {:else if filtered.length === 0}
    <EmptyState
      icon="search"
      title="No matching receipts"
      body="Nothing with that merchant or status. Try clearing the search."
    >
      {#snippet actions()}
        <button
          class="btn"
          onclick={() => {
            search = "";
            filter = "all";
          }}>Clear filters</button
        >
      {/snippet}
    </EmptyState>
  {:else}
    <table class="w-full border-collapse text-[12.5px]">
      <thead>
        <tr class="bg-sunken/60">
          <th class="th">Document</th>
          <th class="th w-28">Date</th>
          <th class="th w-32 text-right">Total</th>
          <th class="th w-32">Status</th>
          <th class="th w-28 text-right">Confidence</th>
        </tr>
      </thead>
      <tbody>
        {#each filtered as d (d.id)}
          <tr class="transition-colors hover:bg-sunken/50">
            <td class="td max-w-0">
              <span class="flex items-center gap-2.5">
                <span
                  class="flex size-7 shrink-0 items-center justify-center rounded-md bg-sunken text-t3"
                >
                  <Icon name="receipt" size={14} />
                </span>
                <span class="min-w-0 leading-tight">
                  <span class="block truncate font-medium">
                    {d.merchant ?? "Awaiting extraction"}
                  </span>
                  <span class="block truncate font-mono text-[10.5px] text-t3">
                    {d.file_name}
                  </span>
                </span>
              </span>
            </td>
            <td class="td num whitespace-nowrap text-t2">
              {d.issued_at ? fmtDate(d.issued_at) : "—"}
            </td>
            <td class="td num text-right">
              {d.total_minor != null ? fmtMoney(-d.total_minor) : "—"}
            </td>
            <td class="td">
              <Badge tone={statusTone[d.status]} label={d.status} />
            </td>
            <td class="td num text-right text-t2">
              {d.extraction ? fmtPct(d.extraction.confidence) : "—"}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  {/if}
</div>
